# Resultados del Análisis Universal POS / Penn Treebank


### IMPORTACIÓN DE LIBRERÍAS Y LLAMADO A LAS FUNCIONES

In [1]:
import pandas as pd

import sys
sys.path.append('../analisisPOS')

from posTreebank import (
    pos_treebank,
    resumen_treebank)

from posUniversal import (
    pos_universal,
    resumen_universal
)

In [2]:
corpus = pd.read_csv('../../data/processed/corpus_Google-Maps-Reviews.csv')

corpus.head(10)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,NaN
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,NaN
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",NaN
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",NaN
5,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps,en,Playa realmente hermosa. Pero ten cuidado con ...,NaN
6,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps,es,Me encantó el agua súper transparente habían p...,NaN
7,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps,en,Hermosas playas en este parque natural. Coment...,NaN
8,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps,es,Paraíso! Dentro de la reserva de encuentra est...,NaN
9,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps,es,"Hermosa playa, tener vudoadi con las corriente...",NaN

## PENN TREEBANK CON NLTK

In [3]:
# ANÁLISIS DE PENN TREEBANK

analisis_treebank = pos_treebank(corpus)

analisis_treebank.head(10)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis,PennTreebank
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,NaN,"[(La, NNP), (playa, FW), (de, FW), (Manuel, NN..."
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊,"[(Una, NNP), (de, FW), (las, FW), (dos, FW), (..."
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,NaN,"[(Playa, NNP), (excepcional, VBZ), (a, DT), (l..."
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",NaN,"[(Para, NNP), (cualquier, NN), (turista, NN), ..."
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",NaN,"[(Bonita, NNP), (playa, NN), (pero, NN), (no, ..."
5,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps,en,Playa realmente hermosa. Pero ten cuidado con ...,NaN,"[(Playa, NNP), (realmente, NN), (hermosa, NN),..."
6,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps,es,Me encantó el agua súper transparente habían p...,NaN,"[(Me, NNP), (encantó, VBZ), (el, JJ), (agua, J..."
7,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps,en,Hermosas playas en este parque natural. Coment...,NaN,"[(Hermosas, NNP), (playas, NN), (en, FW), (est..."
8,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps,es,Paraíso! Dentro de la reserva de encuentra est...,NaN,"[(Paraíso, NN), (!, .), (Dentro, NNP), (de, IN..."
9,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps,es,"Hermosa playa, tener vudoadi con las corriente...",NaN,"[(Hermosa, NNP), (playa, NN), (,, ,), (tener, ..."

## UNIVERSAL POS CON SPACY

In [4]:
# ANÁLISIS DE UNIVERSAL POS
analisis_universal = pos_universal(corpus)

analisis_universal.head(5)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis,UniversalPOS
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,NaN,"[(La, DET, el), (playa, NOUN, playa), (de, ADP..."
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊,"[(Una, PRON, uno), (de, ADP, de), (las, DET, e..."
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,NaN,"[(Playa, PROPN, Playa), (excepcional, ADJ, exc..."
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",NaN,"[(Para, ADP, para), (cualquier, DET, cualquier..."
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",NaN,"[(Bonita, PROPN, Bonita), (playa, PROPN, playa..."

In [21]:
# GUARDADO DE LOS RESULTADOS DEL ANÁLISIS EN UN CORPUS NUEVO

corpus_analisis = corpus.copy() # COPIA DEL ORIGINAL

# INCLUSIÓN DE LAS COLUMNAS CORRESPONDIENTES CON LOS RESULTADOS
corpus_analisis['penntreebank']  = analisis_treebank['PennTreebank']
corpus_analisis['universalpos'] = analisis_universal['UniversalPOS']


# GUARDADO DEL CORPUS EN LA RUTA DETERMINADA
ruta_processed = "../../data/processed/dataset_Google-Maps-Reviews-Scraper-postagging.csv"

corpus_analisis.to_csv(ruta_processed, index=False)
print("Archivo guardado en data/processed")

Archivo guardado en data/processed

### REVIEW Y CONTEO DE LAS ETIQUETAS OTORGADAS POR CADA MÉTODO

In [8]:
resumen_upos = resumen_universal(analisis_universal)
resumen_upos

   etiqueta  total
0      NOUN  11305
1       DET   7305
2     PUNCT   7294
3       ADP   6378
4       ADJ   5928
5      VERB   4970
6       ADV   4003
7       AUX   3185
8      PRON   2716
9     CCONJ   2600
10    PROPN   1664
11    SCONJ   1169
12    SPACE    760
13      NUM    542
14     INTJ     30
15      SYM     16
16     PART      8

In [9]:
resumen_ptb = resumen_treebank(analisis_treebank)
resumen_ptb

   etiqueta  total
0        NN  24178
1        JJ   6710
2        FW   6493
3       NNP   4897
4         .   3991
5         ,   2422
6       NNS   2239
7        IN   1819
8        DT   1295
9       VBP   1221
10      VBZ    895
11      VBD    546
12       CD    451
13       RB    302
14        :    228
15       CC    219
16      PRP    196
17       VB    160
18        )    136
19        (    123
20        $     47
21      JJR     34
22       ''     27
23       ``     26
24       MD     20
25       EX     15
26      VBN     14
27       RP     10
28      RBR      9
29      VBG      8
30       TO      6
31       UH      5
32        #      5
33      RBS      4
34     NNPS      3
35     PRP$      3
36      PDT      2
37      WDT      2
38      SYM      2
39      WRB      1
40      POS      1
41       WP      1